### ISSUE TITLE
RNC_FacebookAppID variable in Info.plist is not match FacebookAppID variable in .env.production

### ISSUE THREAD

**Issue by chellongCoder** [awais-fastian/React-Native-Boilerplate#2]
![image](https://user-images.githubusercontent.com/30166352/91932349-16713900-ed10-11ea-9658-d5d08993ceb5.png)

**Comment by iawaisrana** [comment]
I am using react-native-config and in the latest version for iOS, you have to append RNC_ before key mentioned in the .env.producton or .env.staging

**Comment by iawaisrana** [comment]
@chellongCoder I have updated the info.plist and pre-actions in the scheme, now you can use variables as it is mentioned in the .env files (without RNC_ prefix)

**Comment by chellongCoder** [comment]
dear @awais-fastian I have got an error, seem react-native-config not map variables in .env to info.plist file although I pulled your update
![image](https://user-images.githubusercontent.com/30166352/91935454-ed54a680-ed17-11ea-949b-8a791d07164a.png)

**Comment by iawaisrana** [comment]
@chellongCoder  did you clean the build and build again?

**Comment by chellongCoder** [comment]
@awais-fastian i did. You try clone project again and run it, you will get error like me

**Comment by chellongCoder** [comment]
@awais-fastian please update react-native-config in package-json to 1.3.3
I try it and it works

**Comment by iawaisrana** [comment]
> @awais-fastian please update react-native-config in package-json to 1.3.3
> I try it and it works

@chellongCoder With the same configurations?

**Comment by chellongCoder** [comment]
> > @awais-fastian please update react-native-config in package-json to 1.3.3
> > I try it and it works
> 
> @chellongCoder With the same configurations?

yes! needn't any change, needn't to add RNC_ in info.plist variables

**Comment by iawaisrana** [comment]
update the react-native-config library to version 1.3.3 to resolve the issue
