### ISSUE TITLE
can not use useDispatch()

### ISSUE THREAD

**Issue by kunchit** [awais-fastian/React-Native-Boilerplate#4]
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

**Comment by iawaisrana** [comment]
@kunchit please follow these

go to app/index.js then

`import AppStateProvider from './redux/provider';
`

then wrap NavigationContainer with AppStateProvider like this

`<AppStateProvider>
    <NavigationContainer theme={theme}>
                <AppNavigator />
                <PushNotification />
                <DropdownAlert ref={(ref) => DropDownHolder.setDropDown(ref)} />
              </NavigationContainer>
            </AppStateProvider>`

or you can simply take a pull from the master because I have pushed the change

**Comment by kunchit** [comment]
It works :)
